name: My First actions workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: welcome message
      run: echo "My first Github Actions Job"

    - name: List files
      run: ls

    - name: Read files
      run: cat README.md
