name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./workflows        
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name:  List Repo Files
          run: ls -lrta
        
        - name: Executing shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh

     