name: Exploring Variabes and Secrets

on:
    push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: soggiegithub
  IMAGE_NAME: github-actions-nginx


jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4
          
        - name: Docker Build
          run: docker  build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest .

        - name: Docker Login
          run: docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_GITHUB_TOKEN }}
        
        - name: Docker Publish
          run: |
             docker login -u soggiegithub -p ${{ secrets.DOCKER_GITHUB_TOKEN }}
             docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker run
          run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest